environment:
  matrix:
  - TARGET: 1.24.0-x86_64-pc-windows-msvc
  - TARGET: nightly-x86_64-pc-windows-msvc
  - TARGET: nightly-i686-pc-windows-msvc
  - TARGET: nightly-x86_64-pc-windows-gnu
  - TARGET: nightly-i686-pc-windows-gnu
install:
  - ps: if (ls -r . -fi "*.rs" | sls "`t") { throw "Found tab character" }
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV
build_script:
  - cargo build
test_script:
  - cargo test
