[package]
name = "sharecart1000"
version = "2.0.0-alpha.0"
authors = ["Lokathor <zefria@gmail.com>"]
repository = "https://github.com/Lokathor/sharecart1000-rs"
readme = "README.md"
keywords = ["sharecart", "sharecart1000"]
description = "For use with the Sharecart1000 system."
license = "0BSD"
edition = "2018"

[badges]
appveyor = { repository = "Lokathor/sharecart1000-rs" }
travis-ci = { repository = "Lokathor/sharecart1000-rs" }

[dependencies]
rust-ini = "0.11"
