[package]
name = "sharecart1000"
version = "1.0.0-pre"
authors = ["Lokathor <zefria@gmail.com>"]
repository = "https://github.com/Lokathor/sharecart1000-rs"
readme = "README.md"
keywords = ["retro","bitmap"]
description = "For use with the Sharecart1000 system."
license = "CC0-1.0"

[dependencies]
rust-ini = "0.11"
